services:
  http:
    build: .
    environment:
      NODE_ENV: development
    platform: linux/amd64
    ports:
      - "${HTTP_PORT:-4001}:4001"
    volumes:
      # override packaged /app for dev
      - .:/app
      # node_modules may not be platform compatible,
      # use the container's version stored in the volume instead of the above mount.
      - node_modules:/app/node_modules

volumes:
  node_modules:
